sudo: false
language: node_js
node_js:
- 8
branches:
  only:
  - production
script:
- npm run build
before_deploy:
- PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
- git add -A || true
- git commit -m "build" || true
- git tag -a "v$PACKAGE_VERSION" -m "Version $PACKAGE_VERSION" || true
deploy:
  provider: npm
  email: emilenijssen@gmail.com
  skip_cleanup: true
  api_key:
    secure: ewqVJzmrOO4CI0zL0fwpSrQk1bA6y29Gc+HrVqAuIr1LLtYpgxVgKajVkPYiPiSBMYajd52y1nVU67fbbTQSuEGfbBlKx4SVOMDXQIQMCxGVwa+qkvohH5BY7QjMvRPcnPW1Y6TIMawBqzNN4OfApwlSU5Ev3YBYykpdo2GIvajRzEW4OFU8M+xs9qag6Hi7EfAvnp31VzD9bVSWpA3GhAMZ0ll6UsHSfu9MC35aly3rHh4xxP1IMZqPHJuZttM4O780SO+amqh6BAMQMf/1frRSQraYBcrdBlU9UYf1OahG2o9q85aNfojg+ociMJ5v2rFttxtZy3+qwgu2NG1keSba2fr0RpVwNIJBKEe1hhn/ceR3Rt0BqtT9NZZ13yWZWw+vJn6RchbK5Cir6mWAgK33aDDOzDCmuaOmQEYPrnT3p5xyc1FOo8fmat94m3GWKX6/VV/784jx6a2z9UNahskWNHfPXIF0+uhb5ZZE3+JjC1hvJuXgZ43JEDkg0FYFwbyAZE5P7ucB4tR+ZjbNw+A2dJiHTICeVoBqpSFHs9263HubS02D95kKQveX9O8BiNYfPMEEtocZ37FM3Z72F5JJNS7TB2xJcXiZPXoC4QdTZsqx0ACOPklaG789COmJ84uZTpxA+MbNlS1QrKBoFR2QBlzqNy42dmcXK9zU06c=
  on:
    branch: production
    repo: luxio-lighting/luxio.js
