sudo: false
language: node_js
node_js:
  - 8
branches:
  only:
    - production
script:
  - npm run build
before_deploy:
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  - git add -A || true
  - git commit -m "build" || true
  - git tag -a "v$PACKAGE_VERSION" -m "Version $PACKAGE_VERSION" || true
deploy:
  - provider: npm
    email: emilenijssen@gmail.com
    skip_cleanup: true
    on:
      branch: production
      repo: luxio-lighting/luxio.js
    api_key:
      secure: RSvt+z8BoENbL0L7FuRKlQ5K2QL48Ej4iKMfeH4g/5f61OVgot5dQlide2MoxM9gvgi7CLGBI7/L7j4nTacSpMFKZT476wfRUHf5nake0uKkRJywD1d8bdSZHwCt2/erjfvcCokUroAeKSZwm+wGdmRzXVMECDVhhXpmddjUFZnX6N6x97ZXTCBeFGQf1Hc2I91u90IsQyY+9lANwbf4Lik34K7s33JDIpVk86JeVhPcaZNn+rVmS/Wj/3RFKehA93WyL8w2pLxp+tkXwdd0kYB07cJEiU6c2PAWFI4MqoDmvNUfl2ril+wZGwKv05x91ZgtFExO+KwVpwMSdIjdTJY5/9LePdJLrdbF0W4Phfa1bHifrvwTro/Isg03C2IrQO9CbeeNXmTKc0ncONpQ54tTmrMYOAOi23u0WflkjRQygahkxD7SLq4HsseWPMV1ngXrxVzhvLsK1DLp5WoS6vCjwRwUGXQqv05Ie9CSBNw+nJOx86Lf6UEHG3M+5c08wbkjOmK44tyveqXJHeKLzzPPHIH2BLyXDMCpfAbVnm/ozsiNphwJF1iiDY1X7KNJcAkMIPti/8gIfVobxEOl1HI8Sdluu1wEkD+uJXKMk63j/zdp3gaZ3hMHyAuj8rAhFnp0Iu7j4OWoKSAvJOFH8kfIl7sXIHWKvnapdxf34nw=
  - provider: releases
    skip_cleanup: true
    file:
      - dist/luxio.js
      - dist/luxio.min.js
    on:
      branch: production
      repo: luxio-lighting/luxio.js
    api_key:
      secure: KE3FidQlUgjdHAmsgnd2mEd+59cILhXWDgUgGdjf3C/plN3m7XCKl6OcxplKsk1/HYjz/DrFbILgNw+PvVDD/4tEUIgOYyAooyd02bURfGf9l2hgzdmTVyC7qZNQpJ1MMtFpOYZeqg19uTPVrVbV/fBme8014ZsAawoi+vB1UBomFWlHIlPm+3KViJvUBogdmYh8Bz/WVO954Qxgg8SOgaX97PbDcnKlZ8ARZgGzFH6XSBJ8GP2ZuNILVRu5T6GNhl+LlYhCeBWXHYHuCdxDkP+Xgey6Hog7FOh/4IObjyH/PGmsgM/E9mHfL4gC3+0Q6Mrm28BCK1A09yeQSMnFRs65PF2hgOvqtprJG+im8SN1MAvwEsvz/9o1lRjDAtuyWHbNav8r+shz8y1X6YrdkeFFad89Lw504+AYteq/FpZ9/V28SIJL7lEZJmyEtmku2TzT27+ge9YHJN87mRZD2BLNkFDvZBt/x9cUAZZ/nM5TbHsNNeEB39+q8xvBTZ1tcWgZ9WBlOuTVSart7noKpxslHz82qiIGIO2yotK60AB8d7LFTSZ/jzxKYsHBCkPC/yCVusqj/LgadYAV9St0xnbBKWIunbmGml4F9hhTAmA7/+++MdAOy50MJ3/73QfOjtwTjl1zbRx1iAjU5CS/EiLqKcfh+kjTCwfObUX9Orc=